AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  verifyStravaWebhook:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-verifyStravaWebhook
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: verifyStravaWebhook
      CodeUri: src/verifyStravaWebhook
      Handler: index.handler
      Runtime: nodejs12.x
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
      Environment:
        Variables:
          VERIFY_TOKEN: STRAVA-VRACE
      Events:
        ApiGETvracewebhookstrava:
          Type: Api
          Properties:
            Path: /vrace/webhookstrava
            Method: GET
            RestApiId: !Ref Api
  dataEventFromStrava:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-dataEventFromStrava
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: dataEventFromStrava
      CodeUri: src/dataEventFromStrava
      Handler: index.handler
      Runtime: nodejs12.x
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - DynamoDBCrudPolicy:
            TableName: !Ref vraceEventStrava
        - SQSSendMessagePolicy:
            QueueName: !GetAtt QueueEvents.QueueName
      Environment:
        Variables:
          TABLE_NAME: !Ref vraceEventStrava
          TABLE_ARN: !GetAtt vraceEventStrava.Arn
          QUEUE_NAME: !GetAtt QueueEvents.QueueName
          QUEUE_ARN: !GetAtt QueueEvents.Arn
          QUEUE_URL: !Ref QueueEvents
      Events:
        ApiPOSTvracewebhookstrava:
          Type: Api
          Properties:
            Path: /vrace/webhookstrava
            Method: POST
            RestApiId: !Ref Api
  vraceEventStrava:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: object_id
          AttributeType: 'N'
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: object_id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
  Api:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub
        - ${ResourceName} From Stack ${StackTagName} Environment ${EnvironmentTagName}
        - ResourceName: Api
      StageName: !Ref EnvironmentAPIGatewayStageName
      DefinitionBody:
        swagger: '2.0'
        info: {}
        paths:
          /vrace/webhookstrava:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${verifyStravaWebhook.Arn}/invocations
              responses: {}
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${dataEventFromStrava.Arn}/invocations
              responses: {}
          /vrace/exchangeAutorization:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${exchangeAutorization.Arn}/invocations
              responses: {}
      EndpointConfiguration: REGIONAL
      TracingEnabled: true
  activitiesStrava:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
  QueueEvents:
    Type: AWS::SQS::Queue
    Properties:
      KmsMasterKeyId: alias/aws/sqs
  exchangeAutorization:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-exchangeAutorization
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: exchangeAutorization
      CodeUri: src/exchangeAutorization
      Handler: index.handler
      Runtime: nodejs12.x
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - DynamoDBCrudPolicy:
            TableName: !Ref athleteAutorization
      Events:
        ApiGETvraceexchangeAutorization:
          Type: Api
          Properties:
            Path: /vrace/exchangeAutorization
            Method: GET
            RestApiId: !Ref Api
      Environment:
        Variables:
          TB_ACTIVITIES: !Ref athleteAutorization
          TB_ACTIVITIES_ARN: !GetAtt athleteAutorization.Arn
          C_ID: '54496'
          C_SC: da573e0f74693df6b74a31a5e5ca20ad289e2025
  athleteAutorization:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: 'N'
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
  getActivity:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-getActivity
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: getActivity
      CodeUri: src/getActivity
      Handler: index.handler
      Runtime: nodejs12.x
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - DynamoDBCrudPolicy:
            TableName: !Ref activitiesStrava
        - DynamoDBCrudPolicy:
            TableName: !Ref athleteAutorization
      Environment:
        Variables:
          TB_ACTIVITIES: !Ref activitiesStrava
          TB_ACTIVITIES_ARN: !GetAtt activitiesStrava.Arn
          TB_ATHLETE_AUT: !Ref athleteAutorization
          TB_ATHLETE_AUT_ARN: !GetAtt athleteAutorization.Arn
      Events:
        QueueEvents:
          Type: SQS
          Properties:
            Queue: !GetAtt QueueEvents.Arn
            BatchSize: 1
Parameters:
  StackTagName:
    Type: String
    Description: Stack Name (injected by Stackery at deployment time)
  EnvironmentTagName:
    Type: String
    Description: Environment Name (injected by Stackery at deployment time)
  EnvironmentAPIGatewayStageName:
    Type: String
    Description: Environment name used for API Gateway Stage names (injected by Stackery at deployment time)